[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  publish = "dist"
  port = 5173  # Default Vite port

[build.environment]
  NODE_VERSION = "18"
